"""init schema

Revision ID: 0001
Revises:
Create Date: 2026-05-09 21:33:01.715352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector


# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codes',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_doc_id', sa.String(), nullable=False),
    sa.Column('redaction', sa.String(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_doc_id', name='uq_codes_source_doc')
    )
    op.create_table('structure_nodes',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('parent_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['code_id'], ['codes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['structure_nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_structure_nodes_code_id', 'structure_nodes', ['code_id'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('parent_node_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['code_id'], ['codes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_node_id'], ['structure_nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_id', 'number', name='uq_articles_code_number')
    )
    op.create_table('chunks',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('article_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('code_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('part_number', sa.String(), nullable=True),
    sa.Column('point_number', sa.String(), nullable=True),
    sa.Column('sub_point_number', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column('structure_path', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['code_id'], ['codes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'ordinal', name='uq_chunks_article_id_ordinal')
    )
    op.create_index('ix_chunks_article_id', 'chunks', ['article_id'], unique=False)
    op.create_index('ix_chunks_code_id', 'chunks', ['code_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunks_code_id', table_name='chunks')
    op.drop_index('ix_chunks_article_id', table_name='chunks')
    op.drop_table('chunks')
    op.drop_table('articles')
    op.drop_index('ix_structure_nodes_code_id', table_name='structure_nodes')
    op.drop_table('structure_nodes')
    op.drop_table('codes')
    # ### end Alembic commands ###
